#!/bin/bash


LONG_DATE=`date +%Y%m%d%H%M%S`

/etc/init.d/tomcat6 stop
/etc/init.d/apache2 stop

TOMCAT_USER=tomcat6
TOMCAT_HOME=/var/lib/tomcat6
APACHE_CONF=/etc/apache2
METACAT_VAR=/var/metacat
SOURCE_DIR=/usr/share/metacat
PG=postgresql-8.4
PG_CONF=/etc/postgresql/8.4/main

## drop metacat schema and user
#echo "Dropping metacat database"
#su postgres -c "dropdb metacat"
#echo "Dropping metacat database use metacat"
#su postgres -c "psql --command \"DROP USER metacat\""
##pg_hba.conf was modified, we should probably return it to original

if [ -f ${PG_CONF}/pg_hba.conf.bak ]
then
  rm -f ${PG_CONF}/pg_hba.conf
  mv ${PG_CONF}/pg_hba.conf.bak ${PG_CONF}/pg_hba.conf
  chown postgres ${PG_CONF}/pg_hba.conf
  chgrp postgres ${PG_CONF}/pg_hba.conf
fi

if [ -f ${PG_CONF}/postgresql.conf.bak ]
then
  rm -f ${PG_CONF}/postgresql.conf
  mv ${PG_CONF}/postgresql.conf.bak ${PG_CONF}/postgresql.conf
  chown postgres ${PG_CONF}/postgresql.conf
  chgrp postgres ${PG_CONF}/postgresql.conf	
fi

## Restart the postgres db
echo "Restarting postgres database"
/etc/init.d/${PG} restart

rm -rf ${METACAT_VAR}
rm -rf ${SOURCE_DIR}

rm -rf ${TOMCAT_HOME}/webapps/knb

rm -f ${TOMCAT_HOME}/webapps/knb*
rm -f ${TOMCAT_HOME}/conf/Catalina/localhost/knb.xml

rm -f ${TOMCAT_HOME}/conf/policy.d/51metacat.policy

rm -f ${APACHE_CONF}/jk_mount/knb_jk.*

/etc/init.d/tomcat6 start
/etc/init.d/apache2 start


## Update DateONE Version Info Doc
java -jar /usr/share/dataone-cn-version-tool/dataone-cn-version-tool.jar -F/usr/share/dataone-cn-version-tool/version-tool.properties -html > /var/www/cn-version.html
